module.exports = {
  "extends": "eslint:recommended",
  "env": {
    "node": true
  },
  "rules": {
    // Possible Errors
    "no-console": "off",
    "no-extra-parens": "off",
    "no-prototype-builtins": "off",
    "valid-jsdoc": "off",

    // Best Practices
    "accessor-pairs": "error",
    "array-callback-return": "error",
    "block-scoped-var": "error",
    "complexity": "off",
    "consistent-return": "off",
    "curly": "error",
    "default-case": "off",
    "dot-location": ["error", "property"],
    "dot-notation": "error",
    "eqeqeq": "error",
    "guard-for-in": "off",
    "no-alert": "error",
    "no-caller": "error",
    "no-div-regex": "error",
    "no-else-return": "off",
    "no-empty-function": "off",
    "no-eq-null": "error",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-extra-label": "error",
    "no-floating-decimal": "error",
    "no-implicit-coercion": "error",
    "no-implicit-globals": "error",
    "no-implied-eval": "error",
    "no-invalid-this": "error",
    "no-iterator": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-loop-func": "error",
    "no-magic-numbers": "off",
    "no-multi-spaces": "error",
    "no-multi-str": "error",
    "no-new": "error",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-octal-escape": "error",
    "no-param-reassign": "off",
    "no-proto": "error",
    "no-return-assign": "error",
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-throw-literal": "error",
    "no-unmodified-loop-condition": "error",
    "no-unused-expressions": "error",
    "no-useless-call": "error",
    "no-useless-concat": "error",
    "no-useless-escape": "error",
    "no-void": "error",
    "no-warning-comments": "off",
    "no-with": "error",
    "radix": "error",
    "vars-on-top": "off",
    "wrap-iife": ["error", "inside"],
    "yoda": "off",

    // Strict Mode
    "strict": "error",

    // Variables
    "init-declarations": "off",
    "no-catch-shadow": "error",
    "no-label-var": "error",
    "no-restricted-globals": "off",
    "no-shadow": "error",
    "no-shadow-restricted-names": "error",
    "no-undef-init": "error",
    "no-undefined": "off",
    "no-unused-vars": ["error", {"vars": "all", "args": "all", "argsIgnorePattern": "^_"}],
    "no-use-before-define": ["error", "nofunc"],

    // Node.js and CommonJS
    "callback-return": "off",
    "global-require": "off",
    "handle-callback-err": "off",
    "no-mixed-requires": ["error", {"grouping": true}],
    "no-new-require": "error",
    "no-path-concat": "error",
    "no-process-env": "off",
    "no-process-exit": "off",
    "no-restricted-modules": "off",
    "no-sync": "error",

    // Stylistic Issues
    "array-bracket-spacing": "error",
    "block-spacing": "error",
    "brace-style": "error",
    "camelcase": ["error", {"properties": "never"}],
    "comma-dangle": "error",
    "comma-spacing": "error",
    "comma-style": "error",
    "computed-property-spacing": "error",
    "consistent-this": "off",
    "eol-last": "error",
    "func-names": "error",
    "func-style": ["error", "declaration"],
    "id-blacklist": "off",
    "id-length": "off",
    "id-match": "off",
    "indent": ["error", "tab"],
    "jsx-quotes": "error",
    "key-spacing": "error",
    "keyword-spacing": "error",
    "linebreak-style": "error",
    "lines-around-comment": "off",
    "max-depth": "off",
    "max-len": "off",
    "max-lines": "off",
    "max-nested-callbacks": "off",
    "max-params": "off",
    "max-statements": "off",
    "max-statements-per-line": "off",
    "new-cap": "off",
    "new-parens": "error",
    "newline-after-var": "off",
    "newline-before-return": "off",
    "newline-per-chained-call": "off",
    "no-array-constructor": "error",
    "no-bitwise": "off",
    "no-continue": "off",
    "no-inline-comments": "off",
    "no-lonely-if": "error",
    "no-mixed-operators": "off",
    "no-multiple-empty-lines": "off",
    "no-negated-condition": "off",
    "no-nested-ternary": "off",
    "no-new-object": "error",
    "no-plusplus": "off",
    "no-restricted-syntax": "off",
    "no-spaced-func": "error",
    "no-ternary": "off",
    "no-trailing-spaces": "error",
    "no-underscore-dangle": "off",
    "no-unneeded-ternary": "error",
    "no-whitespace-before-property": "error",
    "object-curly-newline": "off",
    "object-curly-spacing": "error",
    "object-property-newline": "off",
    "one-var": ["error", {"initialized": "never", "uninitialized": "always"}],
    "one-var-declaration-per-line": "off",
    "operator-assignment": "error",
    "operator-linebreak": ["error", "before"],
    "padded-blocks": "off",
    "quote-props": ["error", "as-needed", {"keywords": true, "numbers": true}],
    "quotes": ["error", "single", "avoid-escape"],
    "require-jsdoc": "off",
    "semi": "error",
    "semi-spacing": "error",
    "sort-vars": "off",
    "space-before-blocks": "error",
    "space-before-function-paren": ["error", {"anonymous": "always", "named": "never"}],
    "space-in-parens": "error",
    "space-infix-ops": "error",
    "space-unary-ops": "error",
    "spaced-comment": "error",
    "unicode-bom": "off",
    "wrap-regex": "error"
  }
}
